import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/nav/Navbar";
import Footer from "../components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <NavBar />
        <main className="flex-grow"> {children}</main>

        <Footer />
      </body>
    </html>
  );
}
