import { Inter } from "next/font/google";
import "../globals.css";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface PageProps {
  children: ReactNode,
  params: {
    locale: string
  }
}

export default function RootLayout({ children, params: { locale } }: PageProps) {
  return (
    <html lang={locale}>
      <body className="flex flex-col min-h-screen">
        <main className="flex-grow"> {children}</main>
      </body>
    </html>
  );
}
